### ISSUE TITLE
bluealsa does not support 48k sample rate?

### ISSUE THREAD

**Issue by subjectxbj** [Arkq/bluez-alsa#181]
When I use gstreamer to stream music to BT speaker at sample rate of 16000, it has no problem. But when I resample the music to 48000, then I can't hear any sound on the BT speaker. Does that mean the BT speaker does not support 48000, or the BT data rate can't support 48000, or Bluealsa has problem handling 48000?

Here is the command I used. If I replace 16000 with 48000, then I can't hear the sound on BT speaker.
···
gst-launch-1.0  -vvv audiotestsrc ! audioresample ! audio/x-raw, rate=16000 ! alsasink
···

Here is the log when I stream sound at 48k, I can only hear a short sinewav like 1 second on the BT speaker, then it disapeared.
```
# gst-launch-1.0  -vvv audiotestsrc ! audioresample ! audio/x-raw, rate=48000 ! alsasink
Setting pipeline to PAUSED ...
../../../src/asound/../shared/ctl-client.c:107: Connecting to socket: /var/run/bluealsa/hci0
../../../src/asound/../shared/ctl-client.c:237: Getting transport for 00:12:6F:66:98:B7 type 0x41
../../../src/asound/bluealsa-pcm.c:545: Setting constraints: 8
Pipeline is PREROLLING ...
/GstPipeline:pipeline0/GstAudioTestSrc:audiotestsrc0.GstPad:src: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)48000, channels=(int)2, channel-mask=(bitmask)0x0000000000000003
/GstPipeline:pipeline0/GstAudioResample:audioresample0.GstPad:src: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)48000, channels=(int)2, channel-mask=(bitmask)0x0000000000000003
/GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:src: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)48000, channels=(int)2, channel-mask=(bitmask)0x0000000000000003
../../../src/asound/bluealsa-pcm.c:293: Initializing HW: 8
../../../src/asound/../shared/ctl-client.c:396: Requesting PCM open for 00:12:6F:66:98:B7
../../../src/asound/bluealsa-pcm.c:316: FIFO buffer size: 4096
../../../src/asound/bluealsa-pcm.c:322: Selected HW buffer: 20 periods x 1920 bytes == 38400 bytes
../../../src/asound/bluealsa-pcm.c:337: Initializing SW: 8
../../../src/asound/bluealsa-pcm.c:337: Initializing SW: 8
../../../src/asound/bluealsa-pcm.c:337: Initializing SW: 8
../../../src/asound/bluealsa-pcm.c:337: Initializing SW: 8
../../../src/asound/bluealsa-pcm.c:353: Prepared: 8
../../../src/asound/bluealsa-pcm.c:337: Initializing SW: 8
Redistribute latency...
/GstPipeline:pipeline0/GstAlsaSink:alsasink0.GstPad:sink: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)48000, channels=(int)2, channel-mask=(bitmask)0x0000000000000003
/GstPipeline:pipeline0/GstCapsFilter:capsfilter0.GstPad:sink: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)48000, channels=(int)2, channel-mask=(bitmask)0x0000000000000003
/GstPipeline:pipeline0/GstAudioResample:audioresample0.GstPad:sink: caps = audio/x-raw, format=(string)S16LE, layout=(string)interleaved, rate=(int)48000, channels=(int)2, channel-mask=(bitmask)0x0000000000000003
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstAudioSinkClock
../../../src/asound/bluealsa-pcm.c:225: Starting: 8
../../../src/asound/../shared/ctl-client.c:462: Requesting PCM resume for 00:12:6F:66:98:B7
../../../src/asound/bluealsa-pcm.c:119: Starting IO loop: 14
../../../src/asound/bluealsa-pcm.c:130: IO thread paused: 4
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:03.094146082
Setting pipeline to PAUSED ...
^C
# ^C

```

**Comment by borine** [comment]
Do you export LIBASOUND_THREAD_SAFE=0 in the shell before running your application? I have fond that with alsa-lib v1.1.3 (Ubuntu 18.04) I can play 44.1kHz files successfully but 48000kHz only in mono, not stereo - Wierd! By exporting the above env var before launching my application I find that all my music plays well with Bluealsa.

Please can you report the version of alsa-lib you are using (type aplay --version)
I'm hoping this issue is fixed in alsa-lib 1.1.4 and later, but have not tested it yet.

**Comment by subjectxbj** [comment]
Hi @borine ,

I'm using 1.1.4. sample rate of 44.1kHz works but 48kHz does not work. Even I export LIBASOUND_THREAD_SAFE=0, it still does not work. I have to resample audio from 48kHz to 44.1kHz, then it can work.
